### PR TITLE
Change the way of finding git root to walking up the filesystem

### PR DESCRIPTION
**Pull request by zillding**
## Why

I found this is especially useful in a mono repo context. Sometimes the root folder in the side bar may be a child dir of some git root. 😊 

This is **not** a backward-compatible change.

### CODE REVIEW

**Comment by zillding** [comment]
😊 Can I get some feedback or review on this?

**Comment by braver** [comment]
Sorry, must've missed this one.

The original behaviour is just the way it is because it's easy to implement. There is no need for it any longer with your improvement. Finding the root directory by walking up the filesystem is the way to go. Otherwise you can open Gitup from the sidebar context menu, should you want to be specific about where to go.
We should deal with new buffers that aren't saved to a file yet though. You won't be able to walk the filesystem then and instead should try to do a sensible default, or disable the command.

So, I'd like to have this but done right and without any settings. If you're up to building that, I'll try to give feedback in a timely manner.


Edit:
Although I appreciate backwards compatibility, we don't have enough users to bother with it. Also, we're not getting paid ;) So, keep it simple and move this thing forward.

**Comment by zillding** [comment]
@braver Thanks for the feedback. I have made some changes according to your suggestion.

**Comment by braver** [comment]
Great! 

Because it was originally only able to open from the side-bar root dir, it's disabled on other directories. With your changes it should be able to find the git root from any give path (even if that root not in the sidebar). I think we should at least also update the `is_visible` and `is_enabled` methods that control the availability of the commands in the sidebar context menu. Perhaps we should just update `has_git` so that it does the `climb_dirs` and return true if it finds a git root in any of the parent dirs.

**Comment by zillding** [comment]
💇‍♂️

**Comment by zillding** [comment]
@braver I have made some change. Could you please help review again? 😊

**Comment by braver** [comment]
Thanks! Pretty cool! Final thing: the command only shows in the context menu for folders, but it also works on files (I think it should work at least), so we should show it there as well?

**Comment by zillding** [comment]
@braver Thanks for the review. Updated. 💇‍♂️

**Comment by braver** [comment]
Excellent! 🙇

**Pull request merged**
